return {
    splits = {
        { '<C-h>', function() require('smart-splits').move_cursor_left() end, desc = 'Move to left split' },
        { '<C-j>', function() require('smart-splits').move_cursor_down() end, desc = 'Move to lower split' },
        { '<C-k>', function() require('smart-splits').move_cursor_up() end, desc = 'Move to upper split' },
        { '<C-l>', function() require('smart-splits').move_cursor_right() end, desc = 'Move to right split' },
        { '<A-h>', function() require('smart-splits').resize_left() end, desc = 'Resize left' },
        { '<A-j>', function() require('smart-splits').resize_down() end, desc = 'Resize down' },
        { '<A-k>', function() require('smart-splits').resize_up() end, desc = 'Resize up' },
        { '<A-l>', function() require('smart-splits').resize_right() end, desc = 'Resize right' },
        { '<leader><leader>h', function() require('smart-splits').swap_buf_left() end, desc = 'Swap buffer left' },
        { '<leader><leader>j', function() require('smart-splits').swap_buf_down() end, desc = 'Swap buffer down' },
        { '<leader><leader>k', function() require('smart-splits').swap_buf_up() end, desc = 'Swap buffer up' },
        { '<leader><leader>l', function() require('smart-splits').swap_buf_right() end, desc = 'Swap buffer right' },
    },
    spider = {
        { 'w', function() require('spider').motion('w') end, mode = { 'n', 'o', 'x' }, desc = 'Spider forward' },
        { 'e', function() require('spider').motion('e') end, mode = { 'n', 'o', 'x' }, desc = 'Spider end' },
        { 'b', function() require('spider').motion('b') end, mode = { 'n', 'o', 'x' }, desc = 'Spider backward' },
        { 'ge', function() require('spider').motion('ge') end, mode = { 'n', 'o', 'x' }, desc = 'Spider previous end' },
    },
    maximize = { { '<leader>z', '<cmd>Maximize<cr>', desc = 'Maximize window' } },
    flash = {
        { 'gs', function() require('flash').jump() end, mode = { 'n', 'x', 'o' }, desc = 'Flash jump' },
        {
            'gS',
            function() require('flash').treesitter() end,
            mode = { 'n', 'x', 'o' },
            desc = 'Flash treesitter',
        },
        { 'r', function() require('flash').remote() end, mode = 'o', desc = 'Flash remote' },
        {
            'R',
            function() require('flash').treesitter_search() end,
            mode = { 'o', 'x' },
            desc = 'Flash treesitter search',
        },
        { '<C-s>', function() require('flash').toggle() end, mode = 'c', desc = 'Flash toggle search' },
    },
    glance = {
        { 'gD', '<cmd>Glance definitions<cr>', desc = 'Definitions' },
        { 'gR', '<cmd>Glance references<cr>', desc = 'References' },
        { 'gY', '<cmd>Glance type definitions<cr>', desc = 'Type definitions' },
        { 'gM', '<cmd>Glance implementations<cr>', desc = 'Implementations' },
    },
    oil = { { '-', '<cmd>Oil<cr>', desc = 'Open Oil' } },
    harpoon = {
        { '<leader>a', function() require('harpoon'):list():add() end, desc = 'Harpoon add' },
        {
            '<leader>e',
            function() require('harpoon').ui:toggle_quick_menu(require('harpoon'):list()) end,
            desc = 'Harpoon menu',
        },
        { '<leader>1', function() require('harpoon'):list():select(1) end, desc = 'Harpoon file 1' },
        { '<leader>2', function() require('harpoon'):list():select(2) end, desc = 'Harpoon file 2' },
        { '<leader>3', function() require('harpoon'):list():select(3) end, desc = 'Harpoon file 3' },
        { '<leader>4', function() require('harpoon'):list():select(4) end, desc = 'Harpoon file 4' },
    },
}
