return {
    { import = 'plugins.core' },
    { import = 'plugins.mini' },
    { import = 'plugins.lsp' },
    { import = 'plugins.cmp' },
    { import = 'plugins.edit' },
    { import = 'plugins.nav' },
    { import = 'plugins.git' },
    { import = 'plugins.debug' },
    { import = 'plugins.themes' },
    { import = 'plugins.ui' },
    { import = 'plugins.terminal' },
    { import = 'plugins.extras' },
    { import = 'plugins.ai' },
    { import = 'plugins.lang' },
    { import = 'plugins.42' },
    { import = 'plugins.ts' },
}
