return {
    { import = 'plugins.core' },
    { import = 'plugins.mini' },
    { import = 'plugins.lsp' },
    { import = 'plugins.completion' },
    { import = 'plugins.editor' },
    { import = 'plugins.nav' },
    { import = 'plugins.git' },
    { import = 'plugins.dap' },
    { import = 'plugins.themes' },
    { import = 'plugins.ui' },
    { import = 'plugins.terminal' },
    { import = 'plugins.misc' },
    { import = 'plugins.ai' },
    { import = 'plugins.lang' },
    { import = 'plugins.42' },
    { import = 'plugins.ts' },
}
