return {
    { import = 'plugins.ai' },
    { import = 'plugins.lsp' },
    { import = 'plugins.cmp' },
    { import = 'plugins.nav' },
    { import = 'plugins.git' },
    { import = 'plugins.edit' },
    { import = 'plugins.debug' },
    { import = 'plugins.lint' },
    { import = 'plugins.misc' },
    { import = 'plugins.more' },
    { import = 'plugins.ts' },
    { import = 'plugins.org' },
    { import = 'plugins.lualine' },
    { import = 'plugins.ui' },
}
